[Book]
author = ["Kirjailija", "True"]
title = ["Kirjan nimi", "True"]
year = ["Kirjan julkaisuvuosi", "True"]
publisher = ["Kirjan julkaisija", "True"]
volume = ["Nidos", ""]
number = ["Osa", ""]
pages = ["Sivut", ""]
month = ["Kuukausi", ""]
note = ["Muuta", ""]
doi = ["doi", ""]

[Article]
author = ["Kirjoittaja", "True"]
title = ["Otsikko", "True"]
journal = ["Lehti", "True"]
year = ["Vuosi", "True"]
volume = ["Nidos", ""]
number = ["Osa", ""]
pages = ["Sivut", ""]
month = ["Kuukausi", ""]
note = ["Muuta", ""]